/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openchai_tensorflow_api_PcieDMAServer */

#ifndef _Included_org_openchai_tensorflow_api_PcieDMAServer
#define _Included_org_openchai_tensorflow_api_PcieDMAServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    setupChannelN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_setupChannelN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    registerN
 * Signature: (Lorg/openchai/tensorflow/api/TensorFlowIf/DMACallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_registerN
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    prepareWriteN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_prepareWriteN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    writeN
 * Signature: (Ljava/lang/String;[B)Lorg/openchai/tensorflow/api/DMAStructures/WriteResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_writeN
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    completeWriteN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/WriteResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_completeWriteN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    prepareReadN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_prepareReadN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    readN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/ReadResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_readN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    completeReadN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/ReadResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_completeReadN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    shutdownChannelN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_shutdownChannelN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    readLocalN
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_readLocalN
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
