/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openchai_tensorflow_api_PcieDMAServer */

#ifndef _Included_org_openchai_tensorflow_api_PcieDMAServer
#define _Included_org_openchai_tensorflow_api_PcieDMAServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    setupChannelN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_setupChannelN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    registerN
 * Signature: (Lorg/openchai/tensorflow/api/TensorFlowIf/DMACallback;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_registerN
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    prepareSendN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_prepareSendN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    sendDataN
 * Signature: (Ljava/lang/String;[B)Lorg/openchai/tensorflow/api/DMAStructures/SendResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_sendDataN
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    completeSendN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/SendResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_completeSendN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    prepareRcvN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_prepareRcvN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    rcvDataN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/RcvResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_rcvDataN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    completeRcvN
 * Signature: (Ljava/lang/String;)Lorg/openchai/tensorflow/api/DMAStructures/RcvResultStruct;
 */
JNIEXPORT jobject JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_completeRcvN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    shutdownChannelN
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_shutdownChannelN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openchai_tensorflow_api_PcieDMAServer
 * Method:    readDataN
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_openchai_tensorflow_api_PcieDMAServer_readDataN
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
